### ISSUE TITLE
Error using zeros

### ISSUE THREAD

**Issue by camtboyd** [aelefebv/Mitometer#15]
I get this error when trying to Start3D with a 4.6 gb tif file. Is there a known issue with trying to run large files through Mitometer? I can run smaller files just fine.

> Error using zeros
Size inputs must be integers.

>Error in openTifs (line 39)
        importedImage{i} = zeros(imRows,imCols,numFrames{i}/numZ,numZ,'uint8');

>Error in GUI2/Start3DButtonPushed (line 1222)
                [ImAllTemp,~,fileNameTemp,app.path] = openTifs(app.zPlane); %open all selected images
 
>Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 382)
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by aelefebv** [comment]
Hello!
The issue here is that you probably did not input the correct value when prompted for the number of Z frames. Double check this value and try again. The total number of time frames * z frames divided by your number should be an integer.

In more detail, when starting the run, MATLAB takes in everything except X and Y as a single channel, so I needed to parse those to split up T and Z. When you input the number of Z frames, it divides images into groups based on the total number of images divided by the input number. In your case, it wasn’t an integer so it threw an error.
Feel free to reopen if you still need help!
