### ISSUE TITLE
Errors when running 3D data

### ISSUE THREAD

**Issue by Lufield** [aelefebv/Mitometer#6]
Hi Austin, 
  I am in trouble for processing my 3D data using your grand Mitometer App. It appeared that 2D data could be processed and visualized normally.
 The detailed errors have been listed:
-------------------------------------------------------------------------------------------
Warning: Name is nonexistent or not a directory: E:\Matlab2020b\bin\3D
Error using zeros
Size inputs must be integers.

Error in openTifs (line 39)
        importedImage{i} = zeros(imRows,imCols,numFrames{i}/numZ,numZ,'uint8');

Error in GUI2/Start3DButtonPushed (line 1222)
                [ImAllTemp,~,fileNameTemp,app.path] = openTifs(app.zPlane); %open all selected images
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 386)
Error while evaluating Button PrivateButtonPushedFcn.

Unable to resolve the name IJM.getDatasetAs.

Error in GUI2/IJButton_2Pushed (line 2724)
            evalin('base', 'IJM.getDatasetAs("im")');
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 386)
Error while evaluating Button PrivateButtonPushedFcn.
![github issue1](https://user-images.githubusercontent.com/46242175/133060806-b0b39c7f-f789-4376-bbed-2ea6638525e0.png)

------------------------------------------------------------------------------------------------------
  I would be so appreciated if you could give me some suggestions! 
  Thanks!

Best,
Linker Lu.

**Comment by aelefebv** [comment]
Hi Linker, were you trying to open the 3D image using ImageJ?
More context on the problem would help me figure out the issue.

**Comment by Lufield** [comment]
Yes, I converted my dv data into tiff type using Fiji, and I could open the final 3D image in Fiji. By the way, I tried to apply the 3D data without 3D-projection or Z-projection to Mitometer, then it just failed as I showed before. 
The Matlab version I have installed is 2020b. And the operation system is Windows10. 
As for the parameters of my 3D data:   the pixel size is 0.080594μm, the time interval is 4.8s, the number of z-planes is 89,  and the axial distance is 0.125μm. 
Thank you for your response!  look forward to solve this problem under your assistant.

**Comment by aelefebv** [comment]
Okay great, now can you give me the full dimensions of your image (i.e. x,y,z,t)?

Basically, this error looks like its due to numFrames(i)/numZ not being equal to an integer.
This can occur if you do not input the correct number of z-planes per stack because the app reads the stack as number of zplanes times number of time frames. e.g., if you have 90 z-planes and 20 time frames, you'll have 1800 frames read in. It will then attempt to divide your stack by 90 z-planes to get the amount of time frames out (20). If you input 89 z-planes instead of the correct 90, it'll give a value of 1800/89=20.22 instead of 20 which is not an integer, and thus will give an error.

Hope this makes sense. Let me know if you have questions.

**Comment by Lufield** [comment]
Cool! My problem has been solved after changing the z plane number. Thank you so much!
By the way, I have extended questions: Can I integrate Mitometer from Matlab into some professional softwares (for instance, Amira, Imaris)? Is there any possibility to automatically distinguish some special signals(morphology) from the whole pool.

**Comment by aelefebv** [comment]
With proper credit given, I believe the license gives permission for this integration (but I'm not 100% sure).
When you say special morphologies, what do you mean?
You can, for example, import the objects into matlab via the saved .mat file, and do as you wish with it.

I'm going to close this thread for now since your original issue was solved, but please don't hesitate to message me separately or open a new thread if you have other questions!

**Comment by Lufield** [comment]
Thank you!
